baseurl = "https://www.graphql-java.com"
languageCode = "en-us"
title = "GraphQL Java"
description = "The go to place to learn more about GraphQL Java"
theme = "kube"
pygmentsUseClasses = true

Paginate = 8

[Params]
  RSSLink = "/index.xml"
  author = "GraphQL Java" # add your company name
  github = "graphql-java" # add your github profile name
  twitter = "graphql_java" # add your twitter profile
  email = "contact@graphql-java.com"

[[menu.main]]
    name = "Docs"
    weight = 100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = 200
    url = "/blog/"
[[menu.main]]
    name = "Contact"
    weight = 300
    url = "/contact/"
[[menu.main]]
    name = "About"
    weight = 400
    url = "/about/"
